name: windows-build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build Windows exe with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed --name SnakeGame snake_game.py

      - name: Upload artifact (app folder)
        uses: actions/upload-artifact@v4
        with:
          name: SnakeGame-windows-folder
          path: dist/SnakeGame/

      - name: Upload artifact (single exe)
        uses: actions/upload-artifact@v4
        with:
          name: SnakeGame-windows-exe
          path: dist/SnakeGame/SnakeGame.exe

